/**
 * Seed voice data into database
 */
import { db, schema } from '../src/db/index.js'
import { eq } from 'drizzle-orm'

const voices = [
  { voice_id: "male-qn-qingse", voice_name: "Youthful Male", language: "Chinese" },
  { voice_id: "male-qn-jingying", voice_name: "Elite Young Male", language: "Chinese" },
  { voice_id: "male-qn-badao", voice_name: "Domineering Young Male", language: "Chinese" },
  { voice_id: "male-qn-daxuesheng", voice_name: "College-aged Male", language: "Chinese" },
  { voice_id: "female-shaonv", voice_name: "Young Girl", language: "Chinese" },
  { voice_id: "female-yujie", voice_name: "Mature Woman", language: "Chinese" },
  { voice_id: "female-chengshu", voice_name: "Mature Woman", language: "Chinese" },
  { voice_id: "female-tianmei", voice_name: "Sweet Female", language: "Chinese" },
  { voice_id: "male-qn-qingse-jingpin", voice_name: "Youthful Male-beta", language: "Chinese" },
  { voice_id: "male-qn-jingying-jingpin", voice_name: "Elite Young Male-beta", language: "Chinese" },
  { voice_id: "male-qn-badao-jingpin", voice_name: "Domineering Young Male-beta", language: "Chinese" },
  { voice_id: "male-qn-daxuesheng-jingpin", voice_name: "College-aged Male-beta", language: "Chinese" },
  { voice_id: "female-shaonv-jingpin", voice_name: "Young Girl-beta", language: "Chinese" },
  { voice_id: "female-yujie-jingpin", voice_name: "Mature Woman-beta", language: "Chinese" },
  { voice_id: "female-chengshu-jingpin", voice_name: "Mature Woman-beta", language: "Chinese" },
  { voice_id: "female-tianmei-jingpin", voice_name: "Sweet Female-beta", language: "Chinese" },
  { voice_id: "clever_boy", voice_name: "Clever Boy", language: "Chinese" },
  { voice_id: "cute_boy", voice_name: "Cute Boy", language: "Chinese" },
  { voice_id: "lovely_girl", voice_name: "Cute Little Girl", language: "Chinese" },
  { voice_id: "cartoon_pig", voice_name: "Cartoon Pig Xiaoqi", language: "Chinese" },
  { voice_id: "bingjiao_didi", voice_name: "Yandere Little Brother", language: "Chinese" },
  { voice_id: "junlang_nanyou", voice_name: "Handsome Boyfriend", language: "Chinese" },
  { voice_id: "chunzhen_xuedi", voice_name: "Pure Junior Boy", language: "Chinese" },
  { voice_id: "lengdan_xiongzhang", voice_name: "Cold Senior", language: "Chinese" },
  { voice_id: "badao_shaoye", voice_name: "Domineering Young Master", language: "Chinese" },
  { voice_id: "tianxin_xiaoling", voice_name: "Sweetheart Xiaoling", language: "Chinese" },
  { voice_id: "qiaopi_mengmei", voice_name: "Playful Cute Girl", language: "Chinese" },
  { voice_id: "wumei_yujie", voice_name: "Charming Mature Woman", language: "Chinese" },
  { voice_id: "diadia_xuemei", voice_name: "Sweet Junior Girl", language: "Chinese" },
  { voice_id: "danya_xuejie", voice_name: "Elegant Senior Girl", language: "Chinese" },
  { voice_id: "Santa_Claus ", voice_name: "Santa Claus", language: "English" },
  { voice_id: "Grinch", voice_name: "Grinch", language: "English" },
  { voice_id: "Rudolph", voice_name: "Rudolph", language: "English" },
  { voice_id: "Arnold", voice_name: "Arnold", language: "English" },
  { voice_id: "Charming_Santa", voice_name: "Charming Santa", language: "English" },
  { voice_id: "Charming_Lady", voice_name: "Charming Lady", language: "English" },
  { voice_id: "Sweet_Girl", voice_name: "Sweet Girl", language: "English" },
  { voice_id: "Cute_Elf", voice_name: "Cute Elf", language: "English" },
  { voice_id: "Attractive_Girl", voice_name: "Attractive Girl", language: "English" },
  { voice_id: "Serene_Woman", voice_name: "Serene Woman", language: "English" },
  { voice_id: "Chinese (Mandarin)_Reliable_Executive", voice_name: "Steady Executive", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_News_Anchor", voice_name: "News Anchor Female", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Mature_Woman", voice_name: "Tsundere Mature Woman", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Unrestrained_Young_Man", voice_name: "Unrestrained Youth", language: "Chinese" },
  { voice_id: "Arrogant_Miss", voice_name: "Arrogant Miss", language: "Chinese" },
  { voice_id: "Robot_Armor", voice_name: "Mechanical Armor", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Kind-hearted_Antie", voice_name: "Warm Auntie", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_HK_Flight_Attendant", voice_name: "HK Mandarin Flight Attendant", language: "Cantonese" },
  { voice_id: "Chinese (Mandarin)_Humorous_Elder", voice_name: "Funny Old Man", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Gentleman", voice_name: "Warm Male", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Warm_Bestie", voice_name: "Warm Best Friend", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Male_Announcer", voice_name: "Announcer Male", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Sweet_Lady", voice_name: "Sweet Female", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Southern_Young_Man", voice_name: "Southern Guy", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Wise_Women", voice_name: "Experienced Elder Sister", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Gentle_Youth", voice_name: "Warm Youth", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Warm_Girl", voice_name: "Warm Girl", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Kind-hearted_Elder", voice_name: "Elderly Grandma", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Cute_Spirit", voice_name: "Cute Silly Creature", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Radio_Host", voice_name: "Radio Male Host", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Lyrical_Voice", voice_name: "Lyrical Male", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Straightforward_Boy", voice_name: "Frank Little Brother", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Sincere_Adult", voice_name: "Sincere Youth", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Gentle_Senior", voice_name: "Gentle Senior Girl", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Stubborn_Friend", voice_name: "Tough Childhood Friend", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Crisp_Girl", voice_name: "Crisp Girl", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Pure-hearted_Boy", voice_name: "Clear Neighbor Boy", language: "Chinese" },
  { voice_id: "Chinese (Mandarin)_Soft_Girl", voice_name: "Soft Girl", language: "Chinese" },
  { voice_id: "Cantonese_ProfessionalHost（F)", voice_name: "Professional Female Host", language: "Cantonese" },
  { voice_id: "Cantonese_GentleLady", voice_name: "Gentle Female", language: "Cantonese" },
  { voice_id: "Cantonese_ProfessionalHost（M)", voice_name: "Professional Male Host", language: "Cantonese" },
  { voice_id: "Cantonese_PlayfulMan", voice_name: "Lively Male", language: "Cantonese" },
  { voice_id: "Cantonese_CuteGirl", voice_name: "Cute Girl", language: "Cantonese" },
  { voice_id: "Cantonese_KindWoman", voice_name: "Kind-hearted Female", language: "Cantonese" },
  { voice_id: "English_Trustworthy_Man", voice_name: "Trustworthy Man", language: "English" },
  { voice_id: "English_Graceful_Lady", voice_name: "Graceful Lady", language: "English" },
  { voice_id: "English_Aussie_Bloke", voice_name: "Aussie Bloke", language: "English" },
  { voice_id: "English_Whispering_girl", voice_name: "Whispering girl", language: "English" },
  { voice_id: "English_Diligent_Man", voice_name: "Diligent Man", language: "English" },
  { voice_id: "English_Gentle-voiced_man", voice_name: "Gentle-voiced man", language: "English" },
  { voice_id: "Japanese_IntellectualSenior", voice_name: "Intellectual Senior", language: "Japanese" },
  { voice_id: "Japanese_DecisivePrincess", voice_name: "Decisive Princess", language: "Japanese" },
  { voice_id: "Japanese_LoyalKnight", voice_name: "Loyal Knight", language: "Japanese" },
  { voice_id: "Japanese_DominantMan", voice_name: "Dominant Man", language: "Japanese" },
  { voice_id: "Japanese_SeriousCommander", voice_name: "Serious Commander", language: "Japanese" },
  { voice_id: "Japanese_ColdQueen", voice_name: "Cold Queen", language: "Japanese" },
  { voice_id: "Japanese_DependableWoman", voice_name: "Dependable Woman", language: "Japanese" },
  { voice_id: "Japanese_GentleButler", voice_name: "Gentle Butler", language: "Japanese" },
  { voice_id: "Japanese_KindLady", voice_name: "Kind Lady", language: "Japanese" },
  { voice_id: "Japanese_CalmLady", voice_name: "Calm Lady", language: "Japanese" },
  { voice_id: "Japanese_OptimisticYouth", voice_name: "Optimistic Youth", language: "Japanese" },
  { voice_id: "Japanese_GenerousIzakayaOwner", voice_name: "Generous Izakaya Owner", language: "Japanese" },
  { voice_id: "Japanese_SportyStudent", voice_name: "Sporty Student", language: "Japanese" },
  { voice_id: "Japanese_InnocentBoy", voice_name: "Innocent Boy", language: "Japanese" },
  { voice_id: "Japanese_GracefulMaiden", voice_name: "Graceful Maiden", language: "Japanese" },
  { voice_id: "Dutch_kindhearted_girl", voice_name: "Kind-hearted girl", language: "Dutch" },
  { voice_id: "Dutch_bossy_leader", voice_name: "Bossy leader", language: "Dutch" },
  { voice_id: "Vietnamese_kindhearted_girl", voice_name: "Kind-hearted girl", language: "Vietnamese" },
  { voice_id: "Korean_SweetGirl", voice_name: "Sweet Girl", language: "Korean" },
  { voice_id: "Korean_CheerfulBoyfriend", voice_name: "Cheerful Boyfriend", language: "Korean" },
  { voice_id: "Korean_EnchantingSister", voice_name: "Enchanting Sister", language: "Korean" },
  { voice_id: "Korean_ShyGirl", voice_name: "Shy Girl", language: "Korean" },
  { voice_id: "Korean_ReliableSister", voice_name: "Reliable Sister", language: "Korean" },
  { voice_id: "Korean_StrictBoss", voice_name: "Strict Boss", language: "Korean" },
  { voice_id: "Korean_SassyGirl", voice_name: "Sassy Girl", language: "Korean" },
  { voice_id: "Korean_ChildhoodFriendGirl", voice_name: "Childhood Friend Girl", language: "Korean" },
  { voice_id: "Korean_PlayboyCharmer", voice_name: "Playboy Charmer", language: "Korean" },
  { voice_id: "Korean_ElegantPrincess", voice_name: "Elegant Princess", language: "Korean" },
  { voice_id: "Korean_BraveFemaleWarrior", voice_name: "Brave Female Warrior", language: "Korean" },
  { voice_id: "Korean_BraveYouth", voice_name: "Brave Youth", language: "Korean" },
  { voice_id: "Korean_CalmLady", voice_name: "Calm Lady", language: "Korean" },
  { voice_id: "Korean_EnthusiasticTeen", voice_name: "Enthusiastic Teen", language: "Korean" },
  { voice_id: "Korean_SoothingLady", voice_name: "Soothing Lady", language: "Korean" },
  { voice_id: "Korean_IntellectualSenior", voice_name: "Intellectual Senior", language: "Korean" },
  { voice_id: "Korean_LonelyWarrior", voice_name: "Lonely Warrior", language: "Korean" },
  { voice_id: "Korean_MatureLady", voice_name: "Mature Lady", language: "Korean" },
  { voice_id: "Korean_InnocentBoy", voice_name: "Innocent Boy", language: "Korean" },
  { voice_id: "Korean_CharmingSister", voice_name: "Charming Sister", language: "Korean" },
  { voice_id: "Korean_AthleticStudent", voice_name: "Athletic Student", language: "Korean" },
  { voice_id: "Korean_BraveAdventurer", voice_name: "Brave Adventurer", language: "Korean" },
  { voice_id: "Korean_CalmGentleman", voice_name: "Calm Gentleman", language: "Korean" },
  { voice_id: "Korean_WiseElf", voice_name: "Wise Elf", language: "Korean" },
  { voice_id: "Korean_CheerfulCoolJunior", voice_name: "Cheerful Cool Junior", language: "Korean" },
  { voice_id: "Korean_DecisiveQueen", voice_name: "Decisive Queen", language: "Korean" },
  { voice_id: "Korean_ColdYoungMan", voice_name: "Cold Young Man", language: "Korean" },
  { voice_id: "Korean_MysteriousGirl", voice_name: "Mysterious Girl", language: "Korean" },
  { voice_id: "Korean_QuirkyGirl", voice_name: "Quirky Girl", language: "Korean" },
  { voice_id: "Korean_ConsiderateSenior", voice_name: "Considerate Senior", language: "Korean" },
  { voice_id: "Korean_CheerfulLittleSister", voice_name: "Cheerful Little Sister", language: "Korean" },
  { voice_id: "Korean_DominantMan", voice_name: "Dominant Man", language: "Korean" },
  { voice_id: "Korean_AirheadedGirl", voice_name: "Airheaded Girl", language: "Korean" },
  { voice_id: "Korean_ReliableYouth", voice_name: "Reliable Youth", language: "Korean" },
  { voice_id: "Korean_FriendlyBigSister", voice_name: "Friendly Big Sister", language: "Korean" },
  { voice_id: "Korean_GentleBoss", voice_name: "Gentle Boss", language: "Korean" },
  { voice_id: "Korean_ColdGirl", voice_name: "Cold Girl", language: "Korean" },
  { voice_id: "Korean_HaughtyLady", voice_name: "Haughty Lady", language: "Korean" },
  { voice_id: "Korean_CharmingElderSister", voice_name: "Charming Elder Sister", language: "Korean" },
  { voice_id: "Korean_IntellectualMan", voice_name: "Intellectual Man", language: "Korean" },
  { voice_id: "Korean_CaringWoman", voice_name: "Caring Woman", language: "Korean" },
  { voice_id: "Korean_WiseTeacher", voice_name: "Wise Teacher", language: "Korean" },
  { voice_id: "Korean_ConfidentBoss", voice_name: "Confident Boss", language: "Korean" },
  { voice_id: "Korean_AthleticGirl", voice_name: "Athletic Girl", language: "Korean" },
  { voice_id: "Korean_PossessiveMan", voice_name: "Possessive Man", language: "Korean" },
  { voice_id: "Korean_GentleWoman", voice_name: "Gentle Woman", language: "Korean" },
  { voice_id: "Korean_CockyGuy", voice_name: "Cocky Guy", language: "Korean" },
  { voice_id: "Korean_ThoughtfulWoman", voice_name: "Thoughtful Woman", language: "Korean" },
  { voice_id: "Korean_OptimisticYouth", voice_name: "Optimistic Youth", language: "Korean" },
  { voice_id: "Spanish_SereneWoman", voice_name: "Serene Woman", language: "Spanish" },
  { voice_id: "Spanish_MaturePartner", voice_name: "Mature Partner", language: "Spanish" },
  { voice_id: "Spanish_CaptivatingStoryteller", voice_name: "Captivating Storyteller", language: "Spanish" },
  { voice_id: "Spanish_Narrator", voice_name: "Narrator", language: "Spanish" },
  { voice_id: "Spanish_WiseScholar", voice_name: "Wise Scholar", language: "Spanish" },
  { voice_id: "Spanish_Kind-heartedGirl", voice_name: "Kind-hearted Girl", language: "Spanish" },
  { voice_id: "Spanish_DeterminedManager", voice_name: "Determined Manager", language: "Spanish" },
  { voice_id: "Spanish_BossyLeader", voice_name: "Bossy Leader", language: "Spanish" },
  { voice_id: "Spanish_ReservedYoungMan", voice_name: "Reserved Young Man", language: "Spanish" },
  { voice_id: "Spanish_ConfidentWoman", voice_name: "Confident Woman", language: "Spanish" },
  { voice_id: "Spanish_ThoughtfulMan", voice_name: "Thoughtful Man", language: "Spanish" },
  { voice_id: "Spanish_Strong-WilledBoy", voice_name: "Strong-willed Boy", language: "Spanish" },
  { voice_id: "Spanish_SophisticatedLady", voice_name: "Sophisticated Lady", language: "Spanish" },
  { voice_id: "Spanish_RationalMan", voice_name: "Rational Man", language: "Spanish" },
  { voice_id: "Spanish_AnimeCharacter", voice_name: "Anime Character", language: "Spanish" },
  { voice_id: "Spanish_Deep-tonedMan", voice_name: "Deep-toned Man", language: "Spanish" },
  { voice_id: "Spanish_Fussyhostess", voice_name: "Fussy hostess", language: "Spanish" },
  { voice_id: "Spanish_SincereTeen", voice_name: "Sincere Teen", language: "Spanish" },
  { voice_id: "Spanish_FrankLady", voice_name: "Frank Lady", language: "Spanish" },
  { voice_id: "Spanish_Comedian", voice_name: "Comedian", language: "Spanish" },
  { voice_id: "Spanish_Debator", voice_name: "Debator", language: "Spanish" },
  { voice_id: "Spanish_ToughBoss", voice_name: "Tough Boss", language: "Spanish" },
  { voice_id: "Spanish_Wiselady", voice_name: "Wise Lady", language: "Spanish" },
  { voice_id: "Spanish_Steadymentor", voice_name: "Steady Mentor", language: "Spanish" },
  { voice_id: "Spanish_Jovialman", voice_name: "Jovial Man", language: "Spanish" },
  { voice_id: "Spanish_SantaClaus", voice_name: "Santa Claus", language: "Spanish" },
  { voice_id: "Spanish_Rudolph", voice_name: "Rudolph", language: "Spanish" },
  { voice_id: "Spanish_Intonategirl", voice_name: "Intonate Girl", language: "Spanish" },
  { voice_id: "Spanish_Arnold", voice_name: "Arnold", language: "Spanish" },
  { voice_id: "Spanish_Ghost", voice_name: "Ghost", language: "Spanish" },
  { voice_id: "Spanish_HumorousElder", voice_name: "Humorous Elder", language: "Spanish" },
  { voice_id: "Spanish_EnergeticBoy", voice_name: "Energetic Boy", language: "Spanish" },
  { voice_id: "Spanish_WhimsicalGirl", voice_name: "Whimsical Girl", language: "Spanish" },
  { voice_id: "Spanish_StrictBoss", voice_name: "Strict Boss", language: "Spanish" },
  { voice_id: "Spanish_ReliableMan", voice_name: "Reliable Man", language: "Spanish" },
  { voice_id: "Spanish_SereneElder", voice_name: "Serene Elder", language: "Spanish" },
  { voice_id: "Spanish_AngryMan", voice_name: "Angry Man", language: "Spanish" },
  { voice_id: "Spanish_AssertiveQueen", voice_name: "Assertive Queen", language: "Spanish" },
  { voice_id: "Spanish_CaringGirlfriend", voice_name: "Caring Girlfriend", language: "Spanish" },
  { voice_id: "Spanish_PowerfulSoldier", voice_name: "Powerful Soldier", language: "Spanish" },
  { voice_id: "Spanish_PassionateWarrior", voice_name: "Passionate Warrior", language: "Spanish" },
  { voice_id: "Spanish_ChattyGirl", voice_name: "Chatty Girl", language: "Spanish" },
  { voice_id: "Spanish_RomanticHusband", voice_name: "Romantic Husband", language: "Spanish" },
  { voice_id: "Spanish_CompellingGirl", voice_name: "Compelling Girl", language: "Spanish" },
  { voice_id: "Spanish_PowerfulVeteran", voice_name: "Powerful Veteran", language: "Spanish" },
  { voice_id: "Spanish_SensibleManager", voice_name: "Sensible Manager", language: "Spanish" },
  { voice_id: "Spanish_ThoughtfulLady", voice_name: "Thoughtful Lady", language: "Spanish" },
  { voice_id: "Portuguese_SentimentalLady", voice_name: "Sentimental Lady", language: "Portuguese" },
  { voice_id: "Portuguese_BossyLeader", voice_name: "Bossy Leader", language: "Portuguese" },
  { voice_id: "Portuguese_Wiselady", voice_name: "Wise lady", language: "Portuguese" },
  { voice_id: "Portuguese_Strong-WilledBoy", voice_name: "Strong-willed Boy", language: "Portuguese" },
  { voice_id: "Portuguese_Deep-VoicedGentleman", voice_name: "Deep-voiced Gentleman", language: "Portuguese" },
  { voice_id: "Portuguese_UpsetGirl", voice_name: "Upset Girl", language: "Portuguese" },
  { voice_id: "Portuguese_PassionateWarrior", voice_name: "Passionate Warrior", language: "Portuguese" },
  { voice_id: "Portuguese_AnimeCharacter", voice_name: "Anime Character", language: "Portuguese" },
  { voice_id: "Portuguese_ConfidentWoman", voice_name: "Confident Woman", language: "Portuguese" },
  { voice_id: "Portuguese_AngryMan", voice_name: "Angry Man", language: "Portuguese" },
  { voice_id: "Portuguese_CaptivatingStoryteller", voice_name: "Captivating Storyteller", language: "Portuguese" },
  { voice_id: "Portuguese_Godfather", voice_name: "Godfather", language: "Portuguese" },
  { voice_id: "Portuguese_ReservedYoungMan", voice_name: "Reserved Young Man", language: "Portuguese" },
  { voice_id: "Portuguese_SmartYoungGirl", voice_name: "Smart Young Girl", language: "Portuguese" },
  { voice_id: "Portuguese_Kind-heartedGirl", voice_name: "Kind-hearted Girl", language: "Portuguese" },
  { voice_id: "Portuguese_Pompouslady", voice_name: "Pompous lady", language: "Portuguese" },
  { voice_id: "Portuguese_Grinch", voice_name: "Grinch", language: "Portuguese" },
  { voice_id: "Portuguese_Debator", voice_name: "Debator", language: "Portuguese" },
  { voice_id: "Portuguese_SweetGirl", voice_name: "Sweet Girl", language: "Portuguese" },
  { voice_id: "Portuguese_AttractiveGirl", voice_name: "Attractive Girl", language: "Portuguese" },
  { voice_id: "Portuguese_ThoughtfulMan", voice_name: "Thoughtful Man", language: "Portuguese" },
  { voice_id: "Portuguese_PlayfulGirl", voice_name: "Playful Girl", language: "Portuguese" },
  { voice_id: "Portuguese_GorgeousLady", voice_name: "Gorgeous Lady", language: "Portuguese" },
  { voice_id: "Portuguese_LovelyLady", voice_name: "Lovely Lady", language: "Portuguese" },
  { voice_id: "Portuguese_SereneWoman", voice_name: "Serene Woman", language: "Portuguese" },
  { voice_id: "Portuguese_SadTeen", voice_name: "Sad Teen", language: "Portuguese" },
  { voice_id: "Portuguese_MaturePartner", voice_name: "Mature Partner", language: "Portuguese" },
  { voice_id: "Portuguese_Comedian", voice_name: "Comedian", language: "Portuguese" },
  { voice_id: "Portuguese_NaughtySchoolgirl", voice_name: "Naughty Schoolgirl", language: "Portuguese" },
  { voice_id: "Portuguese_Narrator", voice_name: "Narrator", language: "Portuguese" },
  { voice_id: "Portuguese_ToughBoss", voice_name: "Tough Boss", language: "Portuguese" },
  { voice_id: "Portuguese_Fussyhostess", voice_name: "Fussy hostess", language: "Portuguese" },
  { voice_id: "Portuguese_Dramatist", voice_name: "Dramatist", language: "Portuguese" },
  { voice_id: "Portuguese_Steadymentor", voice_name: "Steady Mentor", language: "Portuguese" },
  { voice_id: "Portuguese_Jovialman", voice_name: "Jovial Man", language: "Portuguese" },
  { voice_id: "Portuguese_CharmingQueen", voice_name: "Charming Queen", language: "Portuguese" },
  { voice_id: "Portuguese_SantaClaus", voice_name: "Santa Claus", language: "Portuguese" },
  { voice_id: "Portuguese_Rudolph", voice_name: "Rudolph", language: "Portuguese" },
  { voice_id: "Portuguese_Arnold", voice_name: "Arnold", language: "Portuguese" },
  { voice_id: "Portuguese_CharmingSanta", voice_name: "Charming Santa", language: "Portuguese" },
  { voice_id: "Portuguese_CharmingLady", voice_name: "Charming Lady", language: "Portuguese" },
  { voice_id: "Portuguese_Ghost", voice_name: "Ghost", language: "Portuguese" },
  { voice_id: "Portuguese_HumorousElder", voice_name: "Humorous Elder", language: "Portuguese" },
  { voice_id: "Portuguese_CalmLeader", voice_name: "Calm Leader", language: "Portuguese" },
  { voice_id: "Portuguese_GentleTeacher", voice_name: "Gentle Teacher", language: "Portuguese" },
  { voice_id: "Portuguese_EnergeticBoy", voice_name: "Energetic Boy", language: "Portuguese" },
  { voice_id: "Portuguese_ReliableMan", voice_name: "Reliable Man", language: "Portuguese" },
  { voice_id: "Portuguese_SereneElder", voice_name: "Serene Elder", language: "Portuguese" },
  { voice_id: "Portuguese_GrimReaper", voice_name: "Grim Reaper", language: "Portuguese" },
  { voice_id: "Portuguese_AssertiveQueen", voice_name: "Assertive Queen", language: "Portuguese" },
  { voice_id: "Portuguese_WhimsicalGirl", voice_name: "Whimsical Girl", language: "Portuguese" },
  { voice_id: "Portuguese_StressedLady", voice_name: "Stressed Lady", language: "Portuguese" },
  { voice_id: "Portuguese_FriendlyNeighbor", voice_name: "Friendly Neighbor", language: "Portuguese" },
  { voice_id: "Portuguese_CaringGirlfriend", voice_name: "Caring Girlfriend", language: "Portuguese" },
  { voice_id: "Portuguese_PowerfulSoldier", voice_name: "Powerful Soldier", language: "Portuguese" },
  { voice_id: "Portuguese_FascinatingBoy", voice_name: "Fascinating Boy", language: "Portuguese" },
  { voice_id: "Portuguese_RomanticHusband", voice_name: "Romantic Husband", language: "Portuguese" },
  { voice_id: "Portuguese_StrictBoss", voice_name: "Strict Boss", language: "Portuguese" },
  { voice_id: "Portuguese_InspiringLady", voice_name: "Inspiring Lady", language: "Portuguese" },
  { voice_id: "Portuguese_PlayfulSpirit", voice_name: "Playful Spirit", language: "Portuguese" },
  { voice_id: "Portuguese_ElegantGirl", voice_name: "Elegant Girl", language: "Portuguese" },
  { voice_id: "Portuguese_CompellingGirl", voice_name: "Compelling Girl", language: "Portuguese" },
  { voice_id: "Portuguese_PowerfulVeteran", voice_name: "Powerful Veteran", language: "Portuguese" },
  { voice_id: "Portuguese_SensibleManager", voice_name: "Sensible Manager", language: "Portuguese" },
  { voice_id: "Portuguese_ThoughtfulLady", voice_name: "Thoughtful Lady", language: "Portuguese" },
  { voice_id: "Portuguese_TheatricalActor", voice_name: "Theatrical Actor", language: "Portuguese" },
  { voice_id: "Portuguese_FragileBoy", voice_name: "Fragile Boy", language: "Portuguese" },
  { voice_id: "Portuguese_ChattyGirl", voice_name: "Chatty Girl", language: "Portuguese" },
  { voice_id: "Portuguese_Conscientiousinstructor", voice_name: "Conscientious Instructor", language: "Portuguese" },
  { voice_id: "Portuguese_RationalMan", voice_name: "Rational Man", language: "Portuguese" },
  { voice_id: "Portuguese_WiseScholar", voice_name: "Wise Scholar", language: "Portuguese" },
  { voice_id: "Portuguese_FrankLady", voice_name: "Frank Lady", language: "Portuguese" },
  { voice_id: "Portuguese_DeterminedManager", voice_name: "Determined Manager", language: "Portuguese" },
  { voice_id: "French_Male_Speech_New", voice_name: "Level-Headed Man", language: "French" },
  { voice_id: "French_Female_News Anchor", voice_name: "Patient Female Presenter", language: "French" },
  { voice_id: "French_CasualMan", voice_name: "Casual Man", language: "French" },
  { voice_id: "French_MovieLeadFemale", voice_name: "Movie Lead Female", language: "French" },
  { voice_id: "French_FemaleAnchor", voice_name: "Female Anchor", language: "French" },
  { voice_id: "French_MaleNarrator", voice_name: "Male Narrator", language: "French" },
  { voice_id: "Indonesian_SweetGirl", voice_name: "Sweet Girl", language: "Indonesian" },
  { voice_id: "Indonesian_ReservedYoungMan", voice_name: "Reserved Young Man", language: "Indonesian" },
  { voice_id: "Indonesian_CharmingGirl", voice_name: "Charming Girl", language: "Indonesian" },
  { voice_id: "Indonesian_CalmWoman", voice_name: "Calm Woman", language: "Indonesian" },
  { voice_id: "Indonesian_ConfidentWoman", voice_name: "Confident Woman", language: "Indonesian" },
  { voice_id: "Indonesian_CaringMan", voice_name: "Caring Man", language: "Indonesian" },
  { voice_id: "Indonesian_BossyLeader", voice_name: "Bossy Leader", language: "Indonesian" },
  { voice_id: "Indonesian_DeterminedBoy", voice_name: "Determined Boy", language: "Indonesian" },
  { voice_id: "Indonesian_GentleGirl", voice_name: "Gentle Girl", language: "Indonesian" },
  { voice_id: "German_FriendlyMan", voice_name: "Friendly Man", language: "German" },
  { voice_id: "German_SweetLady", voice_name: "Sweet Lady", language: "German" },
  { voice_id: "German_PlayfulMan", voice_name: "Playful Man", language: "German" },
  { voice_id: "Russian_HandsomeChildhoodFriend", voice_name: "Handsome Childhood Friend", language: "Russian" },
  { voice_id: "Russian_BrightHeroine", voice_name: "Bright Queen", language: "Russian" },
  { voice_id: "Russian_AmbitiousWoman", voice_name: "Ambitious Woman", language: "Russian" },
  { voice_id: "Russian_ReliableMan", voice_name: "Reliable Man", language: "Russian" },
  { voice_id: "Russian_CrazyQueen", voice_name: "Crazy Girl", language: "Russian" },
  { voice_id: "Russian_PessimisticGirl", voice_name: "Pessimistic Girl", language: "Russian" },
  { voice_id: "Russian_AttractiveGuy", voice_name: "Attractive Guy", language: "Russian" },
  { voice_id: "Russian_Bad-temperedBoy", voice_name: "Bad-tempered Boy", language: "Russian" },
  { voice_id: "Italian_BraveHeroine", voice_name: "Brave Heroine", language: "Italian" },
  { voice_id: "Italian_Narrator", voice_name: "Narrator", language: "Italian" },
  { voice_id: "Italian_WanderingSorcerer", voice_name: "Wandering Sorcerer", language: "Italian" },
  { voice_id: "Italian_DiligentLeader", voice_name: "Diligent Leader", language: "Italian" },
  { voice_id: "Arabic_CalmWoman", voice_name: "Calm Woman", language: "Arabic" },
  { voice_id: "Arabic_FriendlyGuy", voice_name: "Friendly Guy", language: "Arabic" },
  { voice_id: "Turkish_CalmWoman", voice_name: "Calm Woman", language: "Turkish" },
  { voice_id: "Turkish_Trustworthyman", voice_name: "Trustworthy man", language: "Turkish" },
  { voice_id: "Ukrainian_CalmWoman", voice_name: "Calm Woman", language: "Ukrainian" },
  { voice_id: "Ukrainian_WiseScholar", voice_name: "Wise Scholar", language: "Ukrainian" },
]

const ts = new Date().toISOString()

// Clear old data
db.delete(schema.aiVoices).run()

// Bulk insert
const insertRows = voices.map(v => ({
  voiceId: v.voice_id,
  voiceName: v.voice_name,
  description: '[]',
  language: v.language,
  provider: 'minimax',
  createdAt: ts,
}))

db.insert(schema.aiVoices).values(insertRows).run()

console.log(`✅ Inserted ${voices.length} voices`)
